# ============================================================
# CGen Project Makefile: test_project
# Enhanced with STC (Smart Template Containers) support
# Generated by CGen Makefile Generator
# ============================================================

CC = gcc
TARGET = test_project
SRCDIR = .
BUILDDIR = build
STD = -std=c99
CFLAGS = -std=c99
INCLUDES = -I/Users/sa/projects/cfile/src/cgen/ext/stc/include
SOURCES = $(wildcard $(SRCDIR)/*.c)
OBJECTS = $(SOURCES:$(SRCDIR)/%.c=$(BUILDDIR)/%.o)

# STC (Smart Template Containers) Configuration
STC_INCLUDE = /Users/sa/projects/cfile/src/cgen/ext/stc/include
STC_FLAGS = -DSTC_ENABLED

.PHONY: all
all: test_project

$(BUILDDIR): 
	@mkdir -p $(BUILDDIR)

$(BUILDDIR)/%.o: $(SRCDIR)/%.c
	$(CC) $(STD) $(CFLAGS) $(CPPFLAGS) $(INCLUDES) $(STC_FLAGS) -c $< -o $@

test_project: $(BUILDDIR) $(OBJECTS)
	$(CC) $(OBJECTS) -o $@

.PHONY: clean
clean: 
	@rm -rf $(BUILDDIR)
	@rm -f test_project

.PHONY: help
help: 
	@echo "Available targets:"
	@echo "  all     - Build the project (default)"
	@echo "  clean   - Remove build files"
	@echo "  help    - Show this help message"
	@echo "  Built with STC container support"
