/* Generated by CGen Intelligence Layer */
#include <stdio.h>
#include <stdlib.h>

/* Optimizations applied: 5 transformations */

/* Function: factorial */
int factorial(int VariableInfo(name='n', type_info=TypeInfo(name='int', python_type=None, c_equivalent='int', is_mutable=True, is_nullable=False, constraints=[]), scope='factorial', is_parameter=True, is_declared=True, first_assignment_line=None, usage_count=3, is_modified=False)) {
    /* Function body would be generated here */
    return 0;
}

int main() {
    /* Main function */
    return 0;
}