/* Generated by CGen Intelligence Layer */
/* Optimizations applied: 3 transformations (STC unavailable) */

/* Generated by CGen Intelligence Layer with STC Support */
/* Optimizations applied: STC containers for performance */

// Unsupported type: list
#define T NumbersVec, int

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <stc/vec.h>

// Unsupported type: list

int simple_test(void) {
    NumbersVec numbers = {0};
    NumbersVec_push(&numbers, 42);
    NumbersVec_push(&numbers, 24);
    int total = 0;
    for (c_each(it, NumbersVec, numbers)) {
        int num = *it.ref;
        total += num;
    }
    return total;
}

int main(void) {
    int result = simple_test();
    printf("%s\n", "Result: VAR");
    return 0;
}
