/* Generated by CGen Intelligence Layer */
/* Optimizations applied: 3 transformations */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>

int create_empty_grid(int width, int height) {
    "Create an empty grid filled with dead cells.";
    /* Unsupported statement: AnnAssign */
    /* Unsupported statement: AnnAssign */
    while ((i < height)) {
        /* Unsupported statement: AnnAssign */
        /* Unsupported statement: AnnAssign */
        while ((j < width)) {
            /* Unsupported call */;
            int j = (j + 1);
        }
        /* Unsupported call */;
        int i = (i + 1);
    }
    return grid;
}

int copy_grid(int source, int width, int height) {
    "Create a deep copy of the grid.";
    /* Unsupported statement: AnnAssign */
    /* Unsupported statement: AnnAssign */
    while ((i < height)) {
        /* Unsupported statement: AnnAssign */
        /* Unsupported statement: AnnAssign */
        while ((j < width)) {
            /* Unsupported call */;
            j = (j + 1);
        }
        /* Unsupported call */;
        i = (i + 1);
    }
    return new_grid;
}

void set_cell(int grid, int x, int y, int state, int width, int height) {
    "Set the state of a cell at coordinates (x, y).";
    if (((x >= 0) && (x < width) && (y >= 0) && (y < height))) {
    }
}

int get_cell(int grid, int x, int y, int width, int height) {
    "Get the state of a cell at coordinates (x, y).";
    if (((x >= 0) && (x < width) && (y >= 0) && (y < height))) {
        return /* Unsupported expr: Subscript */;
    }
    return DEAD;
}

int count_live_neighbors(int grid, int x, int y, int width, int height) {
    "Count the number of live neighbors around a cell.";
    /* Unsupported statement: AnnAssign */
    /* Unsupported statement: AnnAssign */
    while ((dx <= 1)) {
        /* Unsupported statement: AnnAssign */
        while ((dy <= 1)) {
            if (((dx != 0) || (dy != 0))) {
                /* Unsupported statement: AnnAssign */
                /* Unsupported statement: AnnAssign */
                if ((get_cell(grid, neighbor_x, neighbor_y, width, height) == ALIVE)) {
                    int count = (count + 1);
                }
            }
            int dy = (dy + 1);
        }
        int dx = (dx + 1);
    }
    return count;
}

int apply_game_rules(int current_state, int live_neighbors) {
    "Apply Conway's Game of Life rules to determine next state.";
    if ((current_state == ALIVE)) {
        if (((live_neighbors == 2) || (live_neighbors == 3))) {
            return ALIVE;
        } else {
            return DEAD;
        }
    } else {
        if ((live_neighbors == 3)) {
            return ALIVE;
        } else {
            return DEAD;
        }
    }
}

int evolve_generation(int grid, int width, int height) {
    "Evolve the grid to the next generation.";
    /* Unsupported statement: AnnAssign */
    /* Unsupported statement: AnnAssign */
    while ((y < height)) {
        /* Unsupported statement: AnnAssign */
        while ((x < width)) {
            /* Unsupported statement: AnnAssign */
            /* Unsupported statement: AnnAssign */
            /* Unsupported statement: AnnAssign */
            set_cell(new_grid, x, y, new_state, width, height);
            x = (x + 1);
        }
        y = (y + 1);
    }
    return new_grid;
}

int count_live_cells(int grid, int width, int height) {
    "Count the total number of live cells in the grid.";
    /* Unsupported statement: AnnAssign */
    /* Unsupported statement: AnnAssign */
    while ((y < height)) {
        /* Unsupported statement: AnnAssign */
        while ((x < width)) {
            if ((get_cell(grid, x, y, width, height) == ALIVE)) {
                count = (count + 1);
            }
            x = (x + 1);
        }
        y = (y + 1);
    }
    return count;
}

void print_grid(int grid, int width, int height) {
    "Print the grid to stdout using ASCII characters.";
    printf("%s\n", "+");
    /* Unsupported statement: AnnAssign */
    while ((i < width)) {
        printf("%s\n", "-");
        i = (i + 1);
    }
    printf("%s\n", "+");
    /* Unsupported statement: AnnAssign */
    while ((y < height)) {
        printf("%s\n", "|");
        /* Unsupported statement: AnnAssign */
        while ((x < width)) {
            if ((get_cell(grid, x, y, width, height) == ALIVE)) {
                printf("%s\n", "*");
            } else {
                printf("%s\n", " ");
            }
            x = (x + 1);
        }
        printf("%s\n", "|");
        y = (y + 1);
    }
    printf("%s\n", "+");
    i = 0;
    while ((i < width)) {
        printf("%s\n", "-");
        i = (i + 1);
    }
    printf("%s\n", "+");
}

void initialize_pattern(int grid, int pattern, int offset_x, int offset_y, int width, int height) {
    "Initialize a pattern on the grid at the specified offset.";
    /* Unsupported statement: AnnAssign */
    /* Unsupported statement: AnnAssign */
    while ((i < pattern_length)) {
        /* Unsupported statement: AnnAssign */
        /* Unsupported statement: AnnAssign */
        /* Unsupported statement: AnnAssign */
        set_cell(grid, x, y, ALIVE, width, height);
        i = (i + 1);
    }
}

void clear_grid(int grid, int width, int height) {
    "Clear all cells in the grid.";
    /* Unsupported statement: AnnAssign */
    while ((y < height)) {
        /* Unsupported statement: AnnAssign */
        while ((x < width)) {
            set_cell(grid, x, y, DEAD, width, height);
            x = (x + 1);
        }
        y = (y + 1);
    }
}

int grids_equal(int grid1, int grid2, int width, int height) {
    "Check if two grids are identical. Returns 1 if equal, 0 if not.";
    /* Unsupported statement: AnnAssign */
    while ((y < height)) {
        /* Unsupported statement: AnnAssign */
        while ((x < width)) {
            if ((get_cell(grid1, x, y, width, height) != get_cell(grid2, x, y, width, height))) {
                return 0;
            }
            x = (x + 1);
        }
        y = (y + 1);
    }
    return 1;
}

int detect_stilllife(int grid, int width, int height) {
    "Detect if the grid is in a still life state. Returns 1 if still, 0 if not.";
    /* Unsupported statement: AnnAssign */
    /* Unsupported statement: AnnAssign */
    return is_equal;
}

int detect_oscillator_period(int grid, int width, int height, int max_period) {
    "Detect oscillator period. Returns period if found, 0 if none detected.";
    /* Unsupported statement: AnnAssign */
    /* Unsupported statement: AnnAssign */
    /* Unsupported statement: AnnAssign */
    while ((generation < max_period)) {
        /* Unsupported statement: AnnAssign */
        while ((i < len(states))) {
            if (grids_equal(current, /* Unsupported expr: Subscript */, width, height)) {
                return (generation - i);
            }
            i = (i + 1);
        }
        /* Unsupported call */;
        int current = evolve_generation(current, width, height);
        int generation = (generation + 1);
    }
    return 0;
}

void simulate_pattern(int pattern, char* pattern_name, int generations, int width, int height) {
    "Simulate a specific pattern for the given number of generations.";
    printf("%d\n", /* Unsupported expr: JoinedStr */);
    printf("%d\n", ("=" * 50));
    /* Unsupported statement: AnnAssign */
    /* Unsupported statement: AnnAssign */
    /* Unsupported statement: AnnAssign */
    initialize_pattern(grid, pattern, offset_x, offset_y, width, height);
    printf("%d\n", /* Unsupported expr: JoinedStr */);
    /* Unsupported statement: AnnAssign */
    printf("%d\n", /* Unsupported expr: JoinedStr */);
    print_grid(grid, width, height);
    printf("\n");
    /* Unsupported statement: AnnAssign */
    while ((gen <= generations)) {
        grid = evolve_generation(grid, width, height);
        int live_count = count_live_cells(grid, width, height);
        printf("%d\n", /* Unsupported expr: JoinedStr */);
        printf("%d\n", /* Unsupported expr: JoinedStr */);
        print_grid(grid, width, height);
        printf("\n");
        if ((live_count == 0)) {
            printf("%d\n", /* Unsupported expr: JoinedStr */);
            /* Unsupported statement: Break */
        }
        if (detect_stilllife(grid, width, height)) {
            printf("%d\n", /* Unsupported expr: JoinedStr */);
            /* Unsupported statement: Break */
        }
        int gen = (gen + 1);
    }
}

void run_pattern_analysis(void) {
    "Run analysis on different patterns.";
    printf("%s\n", "Conway's Game of Life - Pattern Analysis");
    printf("%d\n", ("=" * 60));
    printf("\n");
    printf("%s\n", "GLIDER ANALYSIS:");
    printf("%d\n", ("-" * 30));
    /* Unsupported statement: AnnAssign */
    initialize_pattern(grid, GLIDER_PATTERN, 5, 5, GRID_WIDTH, GRID_HEIGHT);
    /* Unsupported statement: AnnAssign */
    if ((period > 0)) {
        printf("%d\n", /* Unsupported expr: JoinedStr */);
    } else {
        printf("%s\n", "Glider is a spaceship (travels)");
    }
    /* Unsupported statement: AnnAssign */
    printf("%d\n", /* Unsupported expr: JoinedStr */);
    printf("\n");
    printf("%s\n", "BLINKER ANALYSIS:");
    printf("%d\n", ("-" * 30));
    clear_grid(grid, GRID_WIDTH, GRID_HEIGHT);
    initialize_pattern(grid, BLINKER_PATTERN, 10, 10, GRID_WIDTH, GRID_HEIGHT);
    int period = detect_oscillator_period(grid, GRID_WIDTH, GRID_HEIGHT, 10);
    if ((period > 0)) {
        printf("%d\n", /* Unsupported expr: JoinedStr */);
    } else {
        printf("%s\n", "Blinker behavior unclear");
    }
    int live_cells = count_live_cells(grid, GRID_WIDTH, GRID_HEIGHT);
    printf("%d\n", /* Unsupported expr: JoinedStr */);
    printf("\n");
    printf("%s\n", "BEACON ANALYSIS:");
    printf("%d\n", ("-" * 30));
    clear_grid(grid, GRID_WIDTH, GRID_HEIGHT);
    initialize_pattern(grid, BEACON_PATTERN, 15, 8, GRID_WIDTH, GRID_HEIGHT);
    period = detect_oscillator_period(grid, GRID_WIDTH, GRID_HEIGHT, 10);
    if ((period > 0)) {
        printf("%d\n", /* Unsupported expr: JoinedStr */);
    } else {
        printf("%s\n", "Beacon behavior unclear");
    }
    live_cells = count_live_cells(grid, GRID_WIDTH, GRID_HEIGHT);
    printf("%d\n", /* Unsupported expr: JoinedStr */);
    printf("\n");
}

void run_comprehensive_demo(void) {
    "Run comprehensive demonstration of Game of Life patterns.";
    printf("%s\n", "Conway's Game of Life - Comprehensive Demo");
    printf("%d\n", ("=" * 60));
    printf("\n");
    simulate_pattern(BLINKER_PATTERN, "Blinker", 3, 15, 10);
    simulate_pattern(TOAD_PATTERN, "Toad", 3, 20, 12);
    simulate_pattern(BEACON_PATTERN, "Beacon", 3, 20, 12);
    simulate_pattern(GLIDER_PATTERN, "Glider", 8, 25, 15);
    run_pattern_analysis();
}

void calculate_statistics(int grid, int width, int height) {
    "Calculate and display grid statistics.";
    /* Unsupported statement: AnnAssign */
    /* Unsupported statement: AnnAssign */
    /* Unsupported statement: AnnAssign */
    printf("%d\n", /* Unsupported expr: JoinedStr */);
    printf("%d\n", /* Unsupported expr: JoinedStr */);
    printf("%d\n", /* Unsupported expr: JoinedStr */);
    printf("%d\n", /* Unsupported expr: JoinedStr */);
    printf("%d\n", /* Unsupported expr: JoinedStr */);
    if ((total_cells > 0)) {
        /* Unsupported statement: AnnAssign */
        printf("%d\n", /* Unsupported expr: JoinedStr */);
    }
}

void create_random_pattern(int grid, int width, int height, int density) {
    "Create a pseudo-random pattern with specified density (0-100).";
    /* Unsupported statement: AnnAssign */
    /* Unsupported statement: AnnAssign */
    while ((y < height)) {
        /* Unsupported statement: AnnAssign */
        while ((x < width)) {
            int seed = (((seed * 1103515245) + 12345) % pow(2, 31));
            /* Unsupported statement: AnnAssign */
            if ((random_val < density)) {
                set_cell(grid, x, y, ALIVE, width, height);
            } else {
                set_cell(grid, x, y, DEAD, width, height);
            }
            x = (x + 1);
        }
        y = (y + 1);
    }
}

void run_evolution_study(void) {
    "Run a study of evolution from random initial conditions.";
    printf("%s\n", "Evolution Study - Random Initial Conditions");
    printf("%d\n", ("=" * 60));
    printf("\n");
    /* Unsupported statement: AnnAssign */
    create_random_pattern(grid, GRID_WIDTH, GRID_HEIGHT, 25);
    printf("%s\n", "Initial random state (25% density):");
    calculate_statistics(grid, GRID_WIDTH, GRID_HEIGHT);
    print_grid(grid, GRID_WIDTH, GRID_HEIGHT);
    printf("\n");
    /* Unsupported statement: AnnAssign */
    /* Unsupported statement: AnnAssign */
    /* Unsupported statement: AnnAssign */
    while ((generation < max_generations)) {
        grid = evolve_generation(grid, GRID_WIDTH, GRID_HEIGHT);
        generation = (generation + 1);
        /* Unsupported statement: AnnAssign */
        printf("%d\n", /* Unsupported expr: JoinedStr */);
        printf("%d\n", /* Unsupported expr: JoinedStr */);
        /* Unsupported statement: AnnAssign */
        if ((change < 0)) {
            int change = (-change);
        }
        if ((((generation % 5) == 0) || (change > 5) || (current_live_count == 0))) {
            print_grid(grid, GRID_WIDTH, GRID_HEIGHT);
            printf("\n");
        }
        if ((current_live_count == 0)) {
            printf("%s\n", "Population extinct!");
            /* Unsupported statement: Break */
        }
        if ((current_live_count == previous_live_count)) {
            if (detect_stilllife(grid, GRID_WIDTH, GRID_HEIGHT)) {
                printf("%s\n", "Population stabilized (still life)");
                /* Unsupported statement: Break */
            }
        }
        int previous_live_count = current_live_count;
    }
}

void main(void) {
    "Main function to run Game of Life demonstration.";
    printf("%s\n", "Starting Conway's Game of Life simulation...");
    printf("\n");
    run_comprehensive_demo();
    run_evolution_study();
    printf("%s\n", "Game of Life simulation completed!");
}
