/* Generated by CGen Intelligence Layer */
/* Optimizations applied: 3 transformations */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#define GRID_WIDTH 40
#define GRID_HEIGHT 20
#define DEAD 0
#define ALIVE 1
/* Pattern coordinates as arrays */
int glider_pattern[][2] = {{1, 0}, {2, 1}, {0, 2}, {1, 2}, {2, 2}};
int blinker_pattern[][2] = {{1, 0}, {1, 1}, {1, 2}};
int toad_pattern[][2] = {{1, 1}, {2, 1}, {3, 1}, {0, 2}, {1, 2}, {2, 2}};
int beacon_pattern[][2] = {{0, 0}, {1, 0}, {0, 1}, {2, 3}, {3, 2}, {3, 3}};

#define GLIDER_PATTERN_SIZE 5
#define BLINKER_PATTERN_SIZE 3
#define TOAD_PATTERN_SIZE 6
#define BEACON_PATTERN_SIZE 6

int** create_empty_grid(int width, int height) {
    int** grid = {};
    int i = 0;
    while (i < height) {
        int* row = {};
        int j = 0;
        while (j < width) {
            /* row.append() - not implemented */;
            j = (j + 1);
        }
        /* grid.append() - not implemented */;
        i = (i + 1);
    }
    return grid;
}

int** copy_grid(int** source, int width, int height) {
    int** new_grid = {};
    int i = 0;
    while (i < height) {
        int* row = {};
        int j = 0;
        while (j < width) {
            /* row.append() - not implemented */;
            j = (j + 1);
        }
        /* new_grid.append() - not implemented */;
        i = (i + 1);
    }
    return new_grid;
}

void set_cell(int** grid, int x, int y, int state, int width, int height) {
    if ((x >= 0 && x < width && y >= 0 && y < height)) {
    }
}

int get_cell(int** grid, int x, int y, int width, int height) {
    if ((x >= 0 && x < width && y >= 0 && y < height)) {
        return grid[y][x];
    }
    return DEAD;
}

int count_live_neighbors(int** grid, int x, int y, int width, int height) {
    int count = 0;
    int dx = (-1);
    while (dx <= 1) {
        int dy = (-1);
        while (dy <= 1) {
            if ((dx != 0 || dy != 0)) {
                int neighbor_x = (x + dx);
                int neighbor_y = (y + dy);
                if (get_cell(grid, neighbor_x, neighbor_y, width, height) == ALIVE) {
                    count = (count + 1);
                }
            }
            dy = (dy + 1);
        }
        dx = (dx + 1);
    }
    return count;
}

int apply_game_rules(int current_state, int live_neighbors) {
    if (current_state == ALIVE) {
        if ((live_neighbors == 2 || live_neighbors == 3)) {
            return ALIVE;
        } else {
            return DEAD;
        }
    } else {
        if (live_neighbors == 3) {
            return ALIVE;
        } else {
            return DEAD;
        }
    }
}

int** evolve_generation(int** grid, int width, int height) {
    int** new_grid = create_empty_grid(width, height);
    int y = 0;
    while (y < height) {
        int x = 0;
        while (x < width) {
            int current_state = get_cell(grid, x, y, width, height);
            int neighbors = count_live_neighbors(grid, x, y, width, height);
            int new_state = apply_game_rules(current_state, neighbors);
            set_cell(new_grid, x, y, new_state, width, height);
            x = (x + 1);
        }
        y = (y + 1);
    }
    return new_grid;
}

int count_live_cells(int** grid, int width, int height) {
    int count = 0;
    int y = 0;
    while (y < height) {
        int x = 0;
        while (x < width) {
            if (get_cell(grid, x, y, width, height) == ALIVE) {
                count = (count + 1);
            }
            x = (x + 1);
        }
        y = (y + 1);
    }
    return count;
}

void print_grid(int** grid, int width, int height) {
    printf("%s\n", "+");
    int i = 0;
    while (i < width) {
        printf("%s\n", "-");
        i = (i + 1);
    }
    printf("%s\n", "+");
    int y = 0;
    while (y < height) {
        printf("%s\n", "|");
        int x = 0;
        while (x < width) {
            if (get_cell(grid, x, y, width, height) == ALIVE) {
                printf("%s\n", "*");
            } else {
                printf("%s\n", " ");
            }
            x = (x + 1);
        }
        printf("%s\n", "|");
        y = (y + 1);
    }
    printf("%s\n", "+");
    i = 0;
    while (i < width) {
        printf("%s\n", "-");
        i = (i + 1);
    }
    printf("%s\n", "+");
}

void initialize_pattern(int** grid, int pattern[][2], int pattern_size, int offset_x, int offset_y, int width, int height) {
    int i = 0;
    while (i < pattern_size) {
        int x = (pattern[i][0] + offset_x);
        int y = (pattern[i][1] + offset_y);
        set_cell(grid, x, y, ALIVE, width, height);
        i = (i + 1);
    }
}

void clear_grid(int** grid, int width, int height) {
    int y = 0;
    while (y < height) {
        int x = 0;
        while (x < width) {
            set_cell(grid, x, y, DEAD, width, height);
            x = (x + 1);
        }
        y = (y + 1);
    }
}

int grids_equal(int** grid1, int** grid2, int width, int height) {
    int y = 0;
    while (y < height) {
        int x = 0;
        while (x < width) {
            if (get_cell(grid1, x, y, width, height) != get_cell(grid2, x, y, width, height)) {
                return 0;
            }
            x = (x + 1);
        }
        y = (y + 1);
    }
    return 1;
}

int detect_stilllife(int** grid, int width, int height) {
    int** next_gen = evolve_generation(grid, width, height);
    int is_equal = grids_equal(grid, next_gen, width, height);
    return is_equal;
}

int detect_oscillator_period(int** grid, int width, int height, int max_period) {
    int*** states = {};
    int** current = copy_grid(grid, width, height);
    int generation = 0;
    while (generation < max_period) {
        int i = 0;
        while (i < (sizeof(states)/sizeof(states[0]))) {
            if (grids_equal(current, states[i], width, height)) {
                return (generation - i);
            }
            i = (i + 1);
        }
        /* states.append() - not implemented */;
        current = evolve_generation(current, width, height);
        generation = (generation + 1);
    }
    return 0;
}

void simulate_pattern(int pattern[][2], int pattern_size, char* pattern_name, int generations, int width, int height) {
    printf("%s\n", "Simulating VAR pattern:");
    printf("%s\n", "=");
    int** grid = create_empty_grid(width, height);
    int offset_x = ((width / 2) - 5);
    int offset_y = ((height / 2) - 5);
    initialize_pattern(grid, pattern, pattern_size, offset_x, offset_y, width, height);
    printf("%s\n", "Generation 0:");
    int live_count = count_live_cells(grid, width, height);
    printf("%s\n", "Live cells: VAR");
    print_grid(grid, width, height);
    printf("\n");
    int gen = 1;
    while (gen <= generations) {
        grid = evolve_generation(grid, width, height);
        live_count = count_live_cells(grid, width, height);
        printf("%s\n", "Generation VAR:");
        printf("%s\n", "Live cells: VAR");
        print_grid(grid, width, height);
        printf("\n");
        if (live_count == 0) {
            printf("%s\n", "Pattern extinct at generation VAR");
            /* Unsupported statement: Break */
        }
        if (detect_stilllife(grid, width, height)) {
            printf("%s\n", "Still life detected at generation VAR");
            /* Unsupported statement: Break */
        }
        gen = (gen + 1);
    }
}

void run_pattern_analysis(void) {
    printf("%s\n", "Conway's Game of Life - Pattern Analysis");
    printf("%s\n", "=");
    printf("\n");
    printf("%s\n", "GLIDER ANALYSIS:");
    printf("%s\n", "-");
    int** grid = create_empty_grid(GRID_WIDTH, GRID_HEIGHT);
    initialize_pattern(grid, glider_pattern, GLIDER_PATTERN_SIZE, 5, 5, GRID_WIDTH, GRID_HEIGHT);
    int period = detect_oscillator_period(grid, GRID_WIDTH, GRID_HEIGHT, 10);
    if (period > 0) {
        printf("%s\n", "Glider period: VAR generations");
    } else {
        printf("%s\n", "Glider is a spaceship (travels)");
    }
    int live_cells = count_live_cells(grid, GRID_WIDTH, GRID_HEIGHT);
    printf("%s\n", "Initial live cells: VAR");
    printf("\n");
    printf("%s\n", "BLINKER ANALYSIS:");
    printf("%s\n", "-");
    clear_grid(grid, GRID_WIDTH, GRID_HEIGHT);
    initialize_pattern(grid, blinker_pattern, BLINKER_PATTERN_SIZE, 10, 10, GRID_WIDTH, GRID_HEIGHT);
    period = detect_oscillator_period(grid, GRID_WIDTH, GRID_HEIGHT, 10);
    if (period > 0) {
        printf("%s\n", "Blinker period: VAR generations");
    } else {
        printf("%s\n", "Blinker behavior unclear");
    }
    live_cells = count_live_cells(grid, GRID_WIDTH, GRID_HEIGHT);
    printf("%s\n", "Initial live cells: VAR");
    printf("\n");
    printf("%s\n", "BEACON ANALYSIS:");
    printf("%s\n", "-");
    clear_grid(grid, GRID_WIDTH, GRID_HEIGHT);
    initialize_pattern(grid, beacon_pattern, BEACON_PATTERN_SIZE, 15, 8, GRID_WIDTH, GRID_HEIGHT);
    period = detect_oscillator_period(grid, GRID_WIDTH, GRID_HEIGHT, 10);
    if (period > 0) {
        printf("%s\n", "Beacon period: VAR generations");
    } else {
        printf("%s\n", "Beacon behavior unclear");
    }
    live_cells = count_live_cells(grid, GRID_WIDTH, GRID_HEIGHT);
    printf("%s\n", "Initial live cells: VAR");
    printf("\n");
}

void run_comprehensive_demo(void) {
    printf("%s\n", "Conway's Game of Life - Comprehensive Demo");
    printf("%s\n", "=");
    printf("\n");
    simulate_pattern(blinker_pattern, BLINKER_PATTERN_SIZE, "Blinker", 3, 15, 10);
    simulate_pattern(toad_pattern, TOAD_PATTERN_SIZE, "Toad", 3, 20, 12);
    simulate_pattern(beacon_pattern, BEACON_PATTERN_SIZE, "Beacon", 3, 20, 12);
    simulate_pattern(glider_pattern, GLIDER_PATTERN_SIZE, "Glider", 8, 25, 15);
    run_pattern_analysis();
}

void calculate_statistics(int** grid, int width, int height) {
    int live_count = count_live_cells(grid, width, height);
    int total_cells = (width * height);
    int dead_count = (total_cells - live_count);
    printf("%s\n", "Grid Statistics:");
    printf("%s\n", "  Dimensions: VAR x VAR");
    printf("%s\n", "  Total cells: VAR");
    printf("%s\n", "  Live cells: VAR");
    printf("%s\n", "  Dead cells: VAR");
    if (total_cells > 0) {
        double live_percentage = ((live_count * 100.000000) / total_cells);
        printf("%s\n", "  Live percentage: VAR%");
    }
}

void create_random_pattern(int** grid, int width, int height, int density) {
    int seed = 12345;
    int y = 0;
    while (y < height) {
        int x = 0;
        while (x < width) {
            seed = (((seed * 1103515245) + 12345) % 2147483648);
            int random_val = (seed % 100);
            if (random_val < density) {
                set_cell(grid, x, y, ALIVE, width, height);
            } else {
                set_cell(grid, x, y, DEAD, width, height);
            }
            x = (x + 1);
        }
        y = (y + 1);
    }
}

void run_evolution_study(void) {
    printf("%s\n", "Evolution Study - Random Initial Conditions");
    printf("%s\n", "=");
    printf("\n");
    int** grid = create_empty_grid(GRID_WIDTH, GRID_HEIGHT);
    create_random_pattern(grid, GRID_WIDTH, GRID_HEIGHT, 25);
    printf("%s\n", "Initial random state (25% density):");
    calculate_statistics(grid, GRID_WIDTH, GRID_HEIGHT);
    print_grid(grid, GRID_WIDTH, GRID_HEIGHT);
    printf("\n");
    int generation = 0;
    int max_generations = 20;
    int previous_live_count = count_live_cells(grid, GRID_WIDTH, GRID_HEIGHT);
    while (generation < max_generations) {
        grid = evolve_generation(grid, GRID_WIDTH, GRID_HEIGHT);
        generation = (generation + 1);
        int current_live_count = count_live_cells(grid, GRID_WIDTH, GRID_HEIGHT);
        printf("%s\n", "Generation VAR:");
        printf("%s\n", "  Live cells: VAR (change: VAR)");
        int change = (current_live_count - previous_live_count);
        if (change < 0) {
            change = (-change);
        }
        if (((generation % 5) == 0 || change > 5 || current_live_count == 0)) {
            print_grid(grid, GRID_WIDTH, GRID_HEIGHT);
            printf("\n");
        }
        if (current_live_count == 0) {
            printf("%s\n", "Population extinct!");
            /* Unsupported statement: Break */
        }
        if (current_live_count == previous_live_count) {
            if (detect_stilllife(grid, GRID_WIDTH, GRID_HEIGHT)) {
                printf("%s\n", "Population stabilized (still life)");
                /* Unsupported statement: Break */
            }
        }
        previous_live_count = current_live_count;
    }
}

int main(void) {
    printf("%s\n", "Starting Conway's Game of Life simulation...");
    printf("\n");
    run_comprehensive_demo();
    run_evolution_study();
    printf("%s\n", "Game of Life simulation completed!");
    return 0;
}
